// This file is automatically generated. Do not edit it directly.
// ⚠️  ARCHITECTURAL NOTE: The Supabase JS client created here is intentionally NOT used
// for business operations. All API calls go through src/lib/api.ts (fetch to Edge Functions).
// Calling supabase.from(...) directly from components would bypass Edge Function middleware
// (rate limiting, auth, structured logging) — do NOT do it for business logic.
// This file is kept for type generation purposes (types.ts) and potential future auth flows.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});